import os
from dotenv import load_dotenv
from app.get_user_data import content

load_dotenv()

Dataset_dir='./Fixy_RAG/data'
Assets_dir='./Fixy_RAG/assets'

MODEL_NAME = "BAAI/bge-m3" 
INDEX_PATH = f"{Assets_dir}/faiss.index"
TEXTS_PATH = f"{Assets_dir}/texts.json"


INPUT_PDF =f'{Dataset_dir}/Fixy_RAG_Production_English.pdf'
OUTPUT_JSON = f"{Assets_dir}/rag_english_data.json"

MODEL_REPO = "Qwen/Qwen3-4B-GGUF"
MODEL_FILE = "Qwen3-4B-Q6_K.gguf"

SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587

RECIEVER_EMAIL_ADDRESS = os.getenv("RECIEVER_EMAIL")
RECIEVER_EMAIL_PASSWORD = os.getenv("RECIEVER_EMAIL_API_KEY")
SENDER_EMAIL_ADDRESS= os.getenv("SENDER_EMAIL")
SENDER_EMAIL_PASSWORD= os.getenv("SENDER_EMAIL_API_KEY")

CODES = {

    1000: {
        "name": "answer_found",
        "description": "Answer exists in context or reliable knowledge"
    },
    1002: {
        "name": "partial_answer",
        "description": "Context partially answers the question"
    },
    1003: {
        "name": "clarification_needed",
        "description": "User query is unclear"
    },
    2000: {
        "name": "escalate_to_support",
        "description": "No answer → forward to support team"
    },
    3000: {
        "name": "out_of_scope",
        "description": "Question not related to Fixy platform"
    },
    4000: {
        "name": "sensitive",
        "description": "Legal, abuse, fraud, or personal data request"
    },
    5000: {
        "name": "greeting",
        "description": "Initial greeting message. The assistant introduces itself and explains the Fixy platform."
    },
  }

messages = {

    "en": f"""
<!DOCTYPE html>
<html>
<head>
<meta charset="UTF-8">
</head>

<body style="
    font-family: Arial, sans-serif;
    background-color: #f4f7fb;
    padding: 30px;
">

<div style="
    max-width: 700px;
    margin: auto;
    background: white;
    border-radius: 12px;
    overflow: hidden;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
">

    <!-- HEADER -->
    <div style="
        background: #2563eb;
        color: white;
        padding: 25px;
        text-align: center;
    ">
        <h1 style="margin:0;">
            Fixy Support Escalation
        </h1>

        <p style="margin-top:10px;">
            AI Generated Support Ticket
        </p>
    </div>

    <!-- BODY -->
    <div style="padding: 30px;">

        <table style="
            width:100%;
            border-collapse: collapse;
        ">

            <tr>
                <td style="padding:12px; font-weight:bold;">
                    Code
                </td>

                <td style="padding:12px;">
                    {code}
                </td>
            </tr>

            <tr style="background:#f9fafb;">
                <td style="padding:12px; font-weight:bold;">
                    User
                </td>

                <td style="padding:12px;">
                    {user}
                </td>
            </tr>

            <tr>
                <td style="padding:12px; font-weight:bold;">
                    Role
                </td>

                <td style="padding:12px;">
                    {role}
                </td>
            </tr>

            <tr style="background:#f9fafb;">
                <td style="padding:12px; font-weight:bold;">
                    Email
                </td>

                <td style="padding:12px;">
                    {email}
                </td>
            </tr>

            <tr>
                <td style="padding:12px; font-weight:bold;">
                    Type
                </td>

                <td style="padding:12px;">
                    {Type}
                </td>
            </tr>

        </table>

        <!-- QUERY -->
        <div style="
            margin-top:30px;
            padding:20px;
            background:#f3f4f6;
            border-left:5px solid #2563eb;
            border-radius:8px;
        ">

            <h3 style="margin-top:0;">
                User Query
            </h3>

            <p style="
                white-space: pre-wrap;
                line-height:1.7;
            ">
                {query}
            </p>

        </div>

    </div>

    <!-- FOOTER -->
    <div style="
        background:#f9fafb;
        padding:20px;
        text-align:center;
        color:#6b7280;
        font-size:14px;
    ">

        <p>
            Generated by Fixy AI Assistant
        </p>

        <p>
            {time}
        </p>

    </div>

</div>

</body>
</html>
""",


    "ar": f"""
<!DOCTYPE html>
<html dir="rtl">
<head>
<meta charset="UTF-8">
</head>

<body style="
    font-family: Arial, sans-serif;
    background-color: #f4f7fb;
    padding: 30px;
">

<div style="
    max-width: 700px;
    margin: auto;
    background: white;
    border-radius: 12px;
    overflow: hidden;
    box-shadow: 0 4px 12px rgba(0,0,0,0.1);
">

    <!-- HEADER -->
    <div style="
        background: #2563eb;
        color: white;
        padding: 25px;
        text-align: center;
    ">
        <h1 style="margin:0;">
            تحويل طلب إلى دعم Fixy
        </h1>

        <p style="margin-top:10px;">
            تذكرة دعم تم إنشاؤها بواسطة الذكاء الاصطناعي
        </p>
    </div>

    <!-- BODY -->
    <div style="padding: 30px;">

        <table style="
            width:100%;
            border-collapse: collapse;
        ">

            <tr>
                <td style="padding:12px; font-weight:bold;">
                    الكود
                </td>

                <td style="padding:12px;">
                    {code}
                </td>
            </tr>

            <tr style="background:#f9fafb;">
                <td style="padding:12px; font-weight:bold;">
                    المستخدم
                </td>

                <td style="padding:12px;">
                    {user}
                </td>
            </tr>

            <tr>
                <td style="padding:12px; font-weight:bold;">
                    الدور
                </td>

                <td style="padding:12px;">
                    {role}
                </td>
            </tr>

            <tr style="background:#f9fafb;">
                <td style="padding:12px; font-weight:bold;">
                    البريد الإلكتروني
                </td>

                <td style="padding:12px;">
                    {email}
                </td>
            </tr>

            <tr>
                <td style="padding:12px; font-weight:bold;">
                    النوع
                </td>

                <td style="padding:12px;">
                    {Type}
                </td>
            </tr>

        </table>

        <!-- QUERY -->
        <div style="
            margin-top:30px;
            padding:20px;
            background:#f3f4f6;
            border-right:5px solid #2563eb;
            border-radius:8px;
        ">

            <h3 style="margin-top:0;">
                الطلب
            </h3>

            <p style="
                white-space: pre-wrap;
                line-height:1.9;
            ">
                {query}
            </p>

        </div>

    </div>

    <!-- FOOTER -->
    <div style="
        background:#f9fafb;
        padding:20px;
        text-align:center;
        color:#6b7280;
        font-size:14px;
    ">

        <p>
            تم الإنشاء بواسطة مساعد Fixy الذكي
        </p>

        <p>
            {time}
        </p>

    </div>

</div>

</body>
</html>
"""
}